### ISSUE TITLE
Can a message be deleted?

### ISSUE THREAD

**Issue by aliuq** [SideCloudGroup/BetterForward#1]
**Describe the bug**
This is a very good project, but during my use, I found a problem

When I send an error message to the robot and I prepare to cancel the message, the message in the topic still exists. The same is true for editing the message, and the same is true for the robot sending a message to the user.

**Expected behavior**
Delete messages on both the bot and the user's device

**Comment by pplulee** [comment]
Thanks for your feedback. From what I understand, the Telegram bot API doesn't seem to provide notifications of messages being deleted/edited, so the program has no way of knowing if a message has been modified.

If there are methods mentioned in the pyTelegramBotAPI documentation but I haven't found it, please let me know.

**Comment by aliuq** [comment]
@pplulee Thanks for the reply，I tried another robot that forwards messages. It can only edit messages on one side of the robot. It is also invalid for message deletion.

**Comment by pplulee** [comment]
The messages edit handling has now been added in #3 

However, it is not possible to handle message deletion as no API is supported. And there are also restrictions on Bot deleting messages.
