### ISSUE TITLE
能否实现可以编辑和删除已发送给用户的消息

### ISSUE THREAD

**Issue by sd362318** [SideCloudGroup/BetterForward#14]
能否实现可以编辑和删除已发送给用户的消息，因为有时候发送错误的信息给用户会非常尴尬，不知道可否实现相关功能。

Is it possible to implement a feature that allows editing or deleting messages that have already been sent to users? Sometimes sending incorrect information can be quite embarrassing, so I was wondering if such functionality could be added. This would help avoid awkward situations and allow for correcting mistakes after the fact.

**Comment by pplulee** [comment]
消息编辑已经实现了。
https://github.com/SideCloudGroup/BetterForward/blob/5ede4efa3a17f5ca70d2e6f9d460d5dc1f581bc4/main.py#L63

删除功能无法实现，TG未提供监听消息删除的接口，并且对于bot删除消息有一定限制。

**Comment by sd362318** [comment]
这样也可以曲线救国。感谢！
