### ISSUE TITLE
不知如何找到groupId

### ISSUE THREAD

**Issue by mryee2023** [SideCloudGroup/BetterForward#15]
使用方法的第二步：

获取群组 ID。这一步可以通过邀请 [@tg_get_userid_bot](https://t.me/tg_get_userid_bot) 到群组中来完成。出于隐私原因，请在获取群组 ID 后将其移除。

我把tg_get_userid_bot拉到群组里，发什么命令才能看到groupId呢？

**Comment by pplulee** [comment]
这个bot坏了，用这个吧 @getmyid_bot。拉进群发个/start

**Comment by mryee2023** [comment]
> 这个bot坏了，用这个吧 @getmyid_bot。拉进群发个/start

还是不太行，我创建了一个群组，开启了话题模式

<img width="702" alt="SCR-20240803-guef" src="https://github.com/user-attachments/assets/5684d41f-99f8-4f97-a21f-90cc2ab3540d">

拉了 getmyid_bot进群，只有我的id和一个负数chatId，并没有groupId

<img width="1019" alt="SCR-20240803-gvdk" src="https://github.com/user-attachments/assets/d1aec493-c058-4e89-b971-a081de39ca37">

**Comment by pplulee** [comment]
chatid就是，记得带负号

**Comment by mryee2023** [comment]
> chatid就是，记得带负号

2024-08-03 01:26:35 [INFO] 正在启动BetterForward……
Traceback (most recent call last):
  File "/app/main.py", line 854, in <module>
    bot = TGBot(args.token, args.group_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 76, in __init__
    self.bot.set_my_commands([
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 4509, in set_my_commands
    return apihelper.set_my_commands(self.token, commands, scope=scope, language_code=language_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 1336, in set_my_commands
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found


不行的，chat不存在，是不是群组要设为公开？

**Comment by pplulee** [comment]
你的bot在群里吗

**Comment by mryee2023** [comment]
<img width="754" alt="SCR-20240803-ixfl" src="https://github.com/user-attachments/assets/8acb4eac-024c-4ef9-8d47-2c03ba42d6f4">

在群里啊

**Comment by pplulee** [comment]
看一下你环境变量怎么填的

**Comment by mryee2023** [comment]
docker run -d --name tg_bot \
    -e TOKEN=6413123205:AAEk4qtpOCvVVSJwhnAZZ1jJzeY6z0Ymgcc \
    -e GROUP_ID=-1002147318262 \
    -e LANGUAGE=zh_CN \
    -v /root/tg:/app/data \
    --restart unless-stopped \
    pplulee/betterforward:latest


token和group_id都是真实的。

**Comment by pplulee** [comment]
感觉应该是你bot权限问题，你上面截图的“不可访问消息”。你重新拉一下bot进群然后给管理员试试看

还有问题的话，你联系 @SideCloudCSBot 我给你看看
