### ISSUE TITLE
Please add the source from on Android

### ISSUE THREAD

**Issue by aliuq** [SideCloudGroup/BetterForward#5]
**Is your feature request related to a problem? Please describe.**

It is impossible to distinguish the source user on telegram x, there is no clear identification

**Describe the solution you'd like**

Know who sent the message on your phone

![image](https://github.com/SideCloudGroup/BetterForward/assets/11707934/aab6034d-7ffe-444e-b24b-44a2888f34ac)

**Comment by pplulee** [comment]
Telegram X doesn't support topic feature.

**Comment by aliuq** [comment]
> Telegram X doesn't support topic feature.

Thanks Reply
